"""
AI Code Reviewer — Main Streamlit Application
Reviews AI-generated code for syntax errors, logic errors,
security vulnerabilities, and performance issues.
"""

import streamlit as st
from src.reviewer import CodeReviewer
from src.models import ReviewResult
from src.ui import render_results, render_header, render_sidebar

st.set_page_config(
    page_title="AI Code Reviewer",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Load custom CSS
with open("assets/style.css") as f:
    st.markdown(f"<style>{f.read()}</style>", unsafe_allow_html=True)


def main():
    render_header()
    render_sidebar()

    st.markdown("---")

    col1, col2 = st.columns([1, 1], gap="large")

    with col1:
        st.markdown("### 📝 Paste Your Code")

        language = st.selectbox(
            "Language",
            ["Python", "JavaScript", "TypeScript", "Java", "C++", "Go", "Rust", "SQL", "Other"],
            index=0,
        )

        source = st.selectbox(
            "Generated by",
            ["ChatGPT / GPT-4", "Claude", "Gemini", "GitHub Copilot", "Other AI", "Unknown"],
            index=0,
        )

        code_input = st.text_area(
            "Code",
            height=400,
            placeholder="Paste AI-generated code here...",
            label_visibility="collapsed",
        )

        review_btn = st.button("🔍 Review Code", type="primary", use_container_width=True)

    with col2:
        st.markdown("### 📊 Review Results")

        if review_btn:
            if not code_input.strip():
                st.warning("Please paste some code first.")
            else:
                with st.spinner("Analysing code..."):
                    reviewer = CodeReviewer()
                    result: ReviewResult = reviewer.review(
                        code=code_input,
                        language=language,
                        source=source,
                    )
                render_results(result)
        else:
            st.info("Paste your code on the left and click **Review Code** to get started.")

            st.markdown("#### What this tool checks:")
            checks = [
                ("🐛", "Syntax Errors", "Malformed code that won't run"),
                ("🧠", "Logic Errors", "Incorrect algorithms or flawed reasoning"),
                ("🔒", "Security Vulnerabilities", "Injections, hardcoded secrets, unsafe calls"),
                ("⚡", "Performance Issues", "Inefficient patterns, O(n²) loops, memory leaks"),
            ]
            for icon, title, desc in checks:
                st.markdown(f"**{icon} {title}** — {desc}")


if __name__ == "__main__":
    main()
