"""
Core reviewer — calls the Anthropic API and parses structured output.
"""

import json
import os
import re
from typing import Any, Dict, List

import anthropic

try:
    import streamlit as st
    _ST_AVAILABLE = True
except ImportError:
    _ST_AVAILABLE = False

from src.models import Issue, IssueCategory, ReviewResult, Severity


SYSTEM_PROMPT = """You are an expert code reviewer specialising in AI-generated code.
Your job is to find real, actionable issues — not stylistic nitpicks.

You MUST respond with a single valid JSON object and NOTHING ELSE.
No markdown fences, no prose before or after — raw JSON only.

Schema:
{
  "overall_score": <integer 0-100>,
  "summary": "<2-3 sentence plain-English summary>",
  "issues": [
    {
      "category": "<Syntax Error|Logic Error|Security Vulnerability|Performance Issue|Style / Best Practice>",
      "severity": "<critical|high|medium|low|info>",
      "title": "<short title>",
      "description": "<detailed description>",
      "line_number": <integer or null>,
      "code_snippet": "<relevant code snippet or null>",
      "suggestion": "<concrete fix suggestion>"
    }
  ]
}

Severity guide:
- critical: code will crash, data loss, or severe security breach
- high: likely bugs or significant security risk
- medium: logic issues or moderate security concern
- low: performance or best-practice issues
- info: informational observations

Be precise. Only flag real issues. If code is clean, say so in summary and return empty issues array.
Score starts at 100 and is deducted: critical=-25, high=-15, medium=-8, low=-3."""


REVIEW_PROMPT = """Review the following {language} code (generated by {source}).

```{language_lower}
{code}
```

Return your analysis as a JSON object following the schema exactly."""


_CATEGORY_MAP = {
    "Syntax Error": IssueCategory.SYNTAX,
    "Logic Error": IssueCategory.LOGIC,
    "Security Vulnerability": IssueCategory.SECURITY,
    "Performance Issue": IssueCategory.PERFORMANCE,
    "Style / Best Practice": IssueCategory.STYLE,
}

_SEVERITY_MAP = {
    "critical": Severity.CRITICAL,
    "high": Severity.HIGH,
    "medium": Severity.MEDIUM,
    "low": Severity.LOW,
    "info": Severity.INFO,
}


class CodeReviewer:
    def __init__(self):
        api_key = os.environ.get("ANTHROPIC_API_KEY", "")
        if not api_key and _ST_AVAILABLE:
            try:
                api_key = st.secrets.get("ANTHROPIC_API_KEY", "")
            except Exception:
                pass
        self.client = anthropic.Anthropic(api_key=api_key) if api_key else None
        self.model = "claude-sonnet-4-5"

    # ------------------------------------------------------------------
    def review(self, code: str, language: str, source: str) -> ReviewResult:
        if self.client is None:
            return self._demo_result(code, language, source)

        prompt = REVIEW_PROMPT.format(
            language=language,
            language_lower=language.lower(),
            source=source,
            code=code,
        )

        message = self.client.messages.create(
            model=self.model,
            max_tokens=4096,
            system=SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )

        raw = message.content[0].text.strip()
        raw = re.sub(r"^```[a-z]*\n?", "", raw)
        raw = re.sub(r"\n?```$", "", raw)
        match = re.search(r"\{.*\}", raw, re.DOTALL)
        if match:
            raw = match.group(0)
        raw = re.sub(r",\s*([}\]])", r"\1", raw)

        try:
            data: Dict[str, Any] = json.loads(raw)
        except json.JSONDecodeError:
            return ReviewResult(
                language=language,
                source=source,
                code=code,
                issues=[],
                overall_score=0,
                summary="Could not parse the review response. Please try again.",
                model_used=self.model,
            )
        issues = [self._parse_issue(i) for i in data.get("issues", [])]

        return ReviewResult(
            language=language,
            source=source,
            code=code,
            issues=issues,
            overall_score=max(0, min(100, int(data.get("overall_score", 100)))),
            summary=data.get("summary", ""),
            model_used=self.model,
        )

    # ------------------------------------------------------------------
    def _parse_issue(self, raw: Dict[str, Any]) -> Issue:
        category = _CATEGORY_MAP.get(raw.get("category", ""), IssueCategory.STYLE)
        severity = _SEVERITY_MAP.get(raw.get("severity", "info"), Severity.INFO)
        return Issue(
            category=category,
            severity=severity,
            title=raw.get("title", "Unnamed issue"),
            description=raw.get("description", ""),
            line_number=raw.get("line_number"),
            code_snippet=raw.get("code_snippet"),
            suggestion=raw.get("suggestion"),
        )

    # ------------------------------------------------------------------
    def _demo_result(self, code: str, language: str, source: str) -> ReviewResult:
        """Fallback demo result when no API key is set."""
        issues = [
            Issue(
                category=IssueCategory.SECURITY,
                severity=Severity.CRITICAL,
                title="Hardcoded credentials detected",
                description="A password or API key appears to be hardcoded in the source code. This is a serious security risk if committed to version control.",
                line_number=3,
                code_snippet='password = "s3cr3t123"',
                suggestion='Use environment variables: password = os.environ.get("DB_PASSWORD")',
            ),
            Issue(
                category=IssueCategory.PERFORMANCE,
                severity=Severity.HIGH,
                title="Nested loop creates O(n²) complexity",
                description="A nested loop iterates over the same collection twice, leading to quadratic time complexity which will degrade severely on large inputs.",
                line_number=12,
                code_snippet="for i in items:\n    for j in items:",
                suggestion="Use a set or dict for O(1) lookups to bring complexity down to O(n).",
            ),
            Issue(
                category=IssueCategory.LOGIC,
                severity=Severity.MEDIUM,
                title="Off-by-one error in range",
                description="The loop uses range(len(arr)) but accesses arr[i+1], which will raise an IndexError on the last iteration.",
                line_number=21,
                code_snippet="for i in range(len(arr)):\n    print(arr[i+1])",
                suggestion="Change to range(len(arr) - 1) to avoid the out-of-bounds access.",
            ),
            Issue(
                category=IssueCategory.STYLE,
                severity=Severity.LOW,
                title="Missing type annotations",
                description="Function parameters and return types lack annotations, reducing IDE support and readability.",
                suggestion="Add type hints: def process(data: list[str]) -> dict[str, int]:",
            ),
        ]
        return ReviewResult(
            language=language,
            source=source,
            code=code,
            issues=issues,
            overall_score=47,
            summary="⚠️ Demo mode (no API key set). This is a sample result showing the output format. Set ANTHROPIC_API_KEY to enable live AI-powered reviews.",
            model_used="demo",
        )
